patterns.vektor-inc.co.jp へのリンクをつける
vektor-inc/vk-block-patterns pull request #70
Opened 2022-03-18 05:59 UTC by shimotmk

2022-03-30 08:26 UTC, kurudrive commented
@shimotmk 確認しました。ばっちりです。
ドラフトですがまだ懸念事項あります？

2022-03-30 08:45 UTC, kurudrive commented
@shimotmk 
※ 内容確認は既にしてあるので、いつものプルリクの記入事項はナシでも大丈夫です。

2022-03-31 00:40 UTC, shimotmk commented
@kurudrive 
確認ありがとうございます。
issuesの段階で要件が固まっていなかったのでプルリクはドラフト状態にしていました。

出来ればコードレビューをしていただきたいので急ぎでなければ @kurudrive  さん以外のレビューをしていただければ幸いです。

2022-04-05 01:42 UTC, kurudrive commented
@mthaichi @drill-lancer レビューよろしくお願いいたします。

2022-04-05 04:13 UTC, drill-lancer commented on vk-block-patterns.php
>  	add_submenu_page( $parent_slug, $page_title, $menu_title, $capability, $menu_slug, $function = '' );
```suggestion	
	if ('ja' === get_locale() ) {
		add_submenu_page( $parent_slug, $page_title, $menu_title, $capability, $menu_slug, $function = '' );
	}
```

2022-04-05 04:15 UTC, drill-lancer commented
@shimotmk 
- 編集画面の上部のボタンは日本語環境でのみ表示される
- VK Block Patterns 配下のパターンライブラリ は英語環境でも表示される

どちらが正しいのかわかりませんが統一したほうが良いような気がします。
一応日本語環境でも表示される旨を信じて提案しておきました。・

2022-04-05 05:00 UTC, shimotmk commented
@drill-lancer 
ありがとうございます！
確かにメニューのリンクも日本語環境以外は表示を想定していないような気がしたのでコミットしました

2022-04-06 03:12 UTC, shimotmk commented
@kurudrive 
register_settings関連はたしかhamanoさんのcustom-html-block-extensionのコードを参考にさせていただきました

https://github.com/t-hamano/custom-html-block-extension/blob/205459dcd4644d8eac841b4cfdd2581286a8285b/classes/class-admin.php#L124-L151

2022-04-06 16:43 UTC, kurudrive requested changes

2022-04-07 01:00 UTC, shimotmk commented on vk-block-patterns.php
> +	$options['showPatternsLink'] = ( isset( $options['showPatternsLink'] ) ) ? $options['showPatternsLink'] : true;
@kurudrive 
ありがとうございます！
たしかに不要なコードでした

2022-04-07 01:01 UTC, shimotmk commented on src/admin/index.js
> +					変更を保存
ありがとうございます！

2022-04-07 04:47 UTC, kurudrive approved these changes

2022-04-07 04:47 UTC, merged